### PR TITLE
Shared scheme to support distributing with Carthage

### LINKED ISSUE #1: Please Support Cartege !!
please... :)

### PR DESCRIPTION
**Pull request by mccallus**
Closes #1

### CODE REVIEW

**Comment by Vortec4800** [comment]
Great, thanks for sending this in.

It looks like the xcuserdata folder in the Xcode project also got committed, which is generated by Xcode and shouldn't be in the repo. If you could remove those that would be great, if you want to commit a .gitignore file at the project root that excludes this folder for the future that wouldn't be a bad idea.

**Comment by mccallus** [comment]
Fixed. I'm so used to having xcuserdata in my gitignore I didn't notice that it slipped in.

**Comment by Vortec4800** [comment]
Looks like one more file snuck in, can you check it?

**Comment by mccallus** [comment]
Found and removed.

**Pull request merged**
